spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  batch:
    jdbc:
      initialize-schema: always


